"use client";
import React, { useState, useEffect } from "react";
import { db } from "../../lib/firebase";
import { collection, addDoc, onSnapshot, query, orderBy } from "firebase/firestore";
import { CreditCard, Save, Printer, GraduationCap } from "lucide-react";

export default function FeesPage() {
  const [students, setStudents] = useState<any[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [amount, setAmount] = useState(0);
  const [category, setCategory] = useState("Monthly Fee");

  useEffect(() => {
    return onSnapshot(collection(db, "students"), (snap) => {
      setStudents(snap.docs.map(doc => ({ id: doc.id, ...doc.data() })));
    });
  }, []);

  const handleSaveFee = async () => {
    const student = students.find(s => s.id === selectedId);
    if (!student || amount <= 0) return alert("Select student and enter amount");
    
    await addDoc(collection(db, "fees"), {
      studentName: student.fullName,
      grandTotal: Number(amount),
      category,
      date: new Date().toISOString()
    });
    alert("Receipt Saved! Dashboard Updated.");
    setAmount(0);
  };

  const selectedStudent = students.find(s => s.id === selectedId);

  return (
    <div className="p-10 font-sans max-w-7xl mx-auto">
      <h1 className="text-3xl font-black text-[#302B52] mb-10 flex items-center gap-3"><CreditCard size={32} className="text-[#7166F9]"/> Finance Portal</h1>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <div className="bg-white p-10 rounded-[48px] shadow-sm border border-purple-50">
          <h3 className="text-xl font-black mb-8">Generate Fee Receipt</h3>
          <div className="space-y-6">
            <select onChange={(e) => setSelectedId(e.target.value)} className="w-full p-5 bg-[#F8F9FE] rounded-2xl border-none font-bold outline-none">
              <option>Search Student...</option>
              {students.map(s => <option key={s.id} value={s.id}>{s.fullName} - {s.rollNo}</option>)}
            </select>
            <div className="grid grid-cols-2 gap-4">
               <select onChange={(e) => setCategory(e.target.value)} className="w-full p-5 bg-[#F8F9FE] rounded-2xl border-none font-bold outline-none">
                 <option>Monthly Fee</option>
                 <option>Exam Fee</option>
                 <option>Admission Fee</option>
               </select>
               <input type="number" placeholder="Amount (Rs.)" value={amount} onChange={e => setAmount(Number(e.target.value))} className="w-full p-5 bg-[#F8F9FE] rounded-2xl border-none font-bold outline-none" />
            </div>
            <button onClick={handleSaveFee} className="w-full bg-[#302B52] text-white py-6 rounded-3xl font-black text-lg flex items-center justify-center gap-3 shadow-xl hover:bg-[#7166F9] transition-all">
              <Save size={24} /> Save & Print Receipt
            </button>
          </div>
        </div>

        {/* RECEIPT PREVIEW */}
        <div className="bg-white p-10 rounded-[48px] border-4 border-dashed border-[#F8F9FE] text-[#302B52]">
          <div className="text-center mb-8">
            <GraduationCap className="mx-auto text-[#7166F9] mb-2" size={40} />
            <h2 className="text-xl font-black uppercase tracking-tight">Fee Voucher</h2>
          </div>
          <div className="space-y-4 font-bold border-t border-b py-6 border-gray-100">
             <div className="flex justify-between text-gray-400 text-sm uppercase"><span>Student</span> <span className="text-[#302B52]">{selectedStudent?.fullName || "---"}</span></div>
             <div className="flex justify-between text-gray-400 text-sm uppercase"><span>Category</span> <span className="text-[#302B52]">{category}</span></div>
             <div className="flex justify-between pt-4 text-3xl font-black text-[#7166F9]"><span>Total</span> <span>Rs. {amount}</span></div>
          </div>
          <p className="text-center mt-8 text-[10px] font-black text-gray-300 uppercase tracking-widest">System Generated by EduPilot</p>
        </div>
      </div>
    </div>
  );
}
