// lib/events/event-types.ts

export const EVENTS = {
  STUDENT_CREATED: "student.created",
  STUDENT_UPDATED: "student.updated",
  STUDENT_DELETED: "student.deleted",
  STUDENT_PROMOTED: "student.promoted",
  STUDENT_TRANSFERRED: "student.transferred",
  CLASS_CHANGED: "student.class_changed",
  SECTION_CHANGED: "student.section_changed",
  ROLL_NUMBER_CHANGED: "student.roll_number_changed",
  PARENT_LINKED: "student.parent_linked",
  PARENT_UNLINKED: "student.parent_unlinked",
  ADMISSION_APPROVED: "student.admission_approved",
  FEE_COLLECTED: "fee.collected",
  ATTENDANCE_MARKED: "attendance.marked",
  ATTENDANCE_UPDATED: "attendance.updated",
  ATTENDANCE_DELETED: "attendance.deleted",
  ATTENDANCE_IMPORTED: "attendance.imported",
  REPORT_GENERATED: "report.generated",
  STAFF_CREATED: "staff.created",
  STAFF_UPDATED: "staff.updated",
  STAFF_DELETED: "staff.deleted",
  STAFF_ACTIVATED: "staff.activated",
  STAFF_DEACTIVATED: "staff.deactivated",
  STAFF_PROMOTED: "staff.promoted",
  ASSIGNMENT_CREATED: "assignment.created",
  ASSIGNMENT_DELETED: "assignment.deleted",
  ASSIGNMENT_SUBMITTED: "assignment.submitted",
  LESSON_PLAN_CREATED: "lesson_plan.created",
  LESSON_PLAN_DELETED: "lesson_plan.deleted",
  BOOK_CREATED: "book.created",
  BOOK_UPDATED: "book.updated",
  BOOK_DELETED: "book.deleted",
  BEHAVIOR_RECORDED: "behavior.recorded",
  MARKS_ENTERED: "marks.entered",
  MARKS_DELETED: "marks.deleted",
  RESULT_PUBLISHED: "result.published",
  QUIZ_CREATED: "quiz.created",
  QUIZ_SUBMITTED: "quiz.submitted",
  QUIZ_DELETED: "quiz.deleted",
  HOMEWORK_CREATED: "homework.created",
  HOMEWORK_UPDATED: "homework.updated",
  HOMEWORK_DELETED: "homework.deleted",
  ASSIGNMENT_UPDATED: "assignment.updated",
  LESSON_PLAN_UPDATED: "lesson_plan.updated",
  BUS_CREATED: "bus.created",
  BUS_UPDATED: "bus.updated",
  BUS_DELETED: "bus.deleted",
  FEE_UPDATED: "fee.updated",
} as const;

// Typescript Magic for strict typing
export type EventType = typeof EVENTS[keyof typeof EVENTS];
