// services/configuration.service.ts
import { ConfigurationRepository } from "@/repositories/configuration.repository";
import { MasterSchoolConfiguration } from "@/types/configuration";
import { SchoolConfigurationViewModel } from "@/types/viewmodels/school-configuration.viewmodel";
import { ConfigurationHistoryViewModel } from "@/types/viewmodels/configuration-history.viewmodel";
import { mapConfigurationToViewModel } from "@/lib/mappers/configuration.viewmodel.mapper";
import { mapHistory } from "@/lib/mappers/history.mapper";
import { randomUUID } from "crypto";
import { logger } from "@/lib/logger/logger";
import type { IConfigurationService } from "@/interfaces/IConfigurationService";

export class ConfigurationService implements IConfigurationService {
  constructor(private readonly repo = new ConfigurationRepository()) {}

  // 1. Get Configuration for UI (Returns ViewModel)
  async getConfigurationViewModel(tenantId: string): Promise<SchoolConfigurationViewModel | null> {
    const config = await this.repo.getActiveConfiguration(tenantId);
    return mapConfigurationToViewModel(config);
  }

  // 2. Get History for UI (Returns ViewModel Array)
  async getConfigurationHistoryViewModel(tenantId: string): Promise<ConfigurationHistoryViewModel[]> {
    const historyDocs = await this.repo.getConfigurationHistory(tenantId);
    return mapHistory(historyDocs);
  }

  // 3. Save Configuration (Business Logic + Engine Output Mapping)
  async saveAndPublishConfiguration(
    input: any, 
    tenantId: string,
    userId: string
  ): Promise<MasterSchoolConfiguration> {
    
    // Get Previous Config to increment version
    const previous = await this.repo.getActiveConfiguration(tenantId);
    const previousVersion = previous?.version?.number || 0;

    // Extract data generated by the Curriculum Intelligence Engine
    const { schoolProfile, academicStructure } = input;

    // 🛡️ Phase 4: Configuration Validator
    if (!academicStructure || !academicStructure.grades || academicStructure.grades.length === 0) {
      throw new Error("Validation Failed: No classes/grades were generated.");
    }
    if (!academicStructure.allSubjects || academicStructure.allSubjects.length === 0) {
      throw new Error("Validation Failed: No subjects were found for the selected curriculum.");
    }

    // Ensure sections have a default fallback
    const sectionNames: string[] = schoolProfile.sections?.length ? schoolProfile.sections : ["A"];

    // 🚀 Phase 2: Map Engine Output to Domain Models
    const mappedClasses = academicStructure.grades.map((g: any) => ({
      id: g.id || `cls_${g.name}`,
      name: g.name,
      level: g.levelId || g.level || "general",
      // Extract subject names from the scheme of study
      subjects: g.schemeOfStudy?.subjects?.map((s: any) => s.name || s.subjectId) || []
    }));

    const now = new Date().toISOString();
    const newConfig: MasterSchoolConfiguration = {
      id: "current",
      tenantId: tenantId,
      state: "Published",
      metadata: {
        tenantId: tenantId,
        schemaVersion: 2,
        configurationVersion: previousVersion + 1,
        environment: process.env.NODE_ENV as any || "development",
        region: "PK",
        timezone: "Asia/Karachi",
        academicYearId: previous?.metadata.academicYearId || null,
        currentSnapshotId: null,
      },
      version: {
        id: randomUUID(),
        number: previousVersion + 1,
        createdBy: userId,
        createdAt: now,
        publishedBy: userId,
        publishedAt: now,
        reason: "Configured via Autonomous Rules Engine",
        checksum: `ck_${Date.now()}`,
      },
      school: {
        name: schoolProfile.name || "Untitled School",
        type: schoolProfile.type || "Private",
        curriculumId: schoolProfile.curriculumId || "custom",
        boardName: schoolProfile.boardName || "Custom Board",
        country: schoolProfile.country || "PK",
      },
      academic: {
        levels: academicStructure.levels.map((l: any) => l.id || l.name),
        classes: mappedClasses,
        sectionNames,
        subjects: academicStructure.allSubjects.map((s: any) => s.name),
        
        // 🚀 NEW: Save Intelligence Engine Outputs
        requiredLabs: academicStructure.requiredLabs || [],
        requiredTeachers: academicStructure.requiredTeachers || {},
      },
      features: previous?.features || {
        ai: { enabled: true, version: "1.0", permissions: ["admin", "teacher"], beta: false, providers: ["gemini"], activeProvider: "gemini", quota: 1000 },
        library: { enabled: true, version: "1.0", permissions: ["admin", "teacher"], beta: false },
        transport: { enabled: false, version: "1.0", permissions: ["admin"], beta: false },
        fees: { enabled: true, version: "1.0", permissions: ["admin", "accountant"], beta: false },
        attendance: { enabled: true, version: "1.0", permissions: ["admin", "teacher"], beta: false },
        exams: { enabled: true, version: "1.0", permissions: ["admin", "teacher"], beta: false },
      },
    };

    // Save to DB via Repository
    await this.repo.saveConfiguration(tenantId, newConfig);
    logger.info("CONFIGURATION_PUBLISHED", { tenantId, version: newConfig.version.number, userId });
    
    return newConfig;
  }
}

// Export singleton instance
export const configurationService = new ConfigurationService();
