// lib/auth/roles.ts
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    "students.view", "students.create", "students.update", "students.delete",
    "staff.view", "staff.create", "staff.update", "staff.delete",
    "fees.view", "fees.create", "fees.update", "fees.delete",
    "attendance.view", "attendance.create", "attendance.update", "attendance.delete",
    "parents.view", "parents.create", "parents.manage",
    "dashboard.view", "analytics.view",
    "settings.view", "settings.manage",
    "billing.view", "billing.manage",
    "audit.view",
    "ledger.view",
    "buses.view", "buses.create", "buses.update", "buses.delete",
    "homework.create", "homework.view",
    "assignments.view", "assignments.create", "assignments.grade",
    "quizzes.view", "quizzes.create", "quizzes.grade",
    "lessonPlans.create", "lessonPlans.view",
    "videoLectures.view", "videoLectures.create",
    "bookCenter.view", "bookCenter.create", "bookCenter.update", "bookCenter.delete",
    "behavior.view", "behavior.create",
    "skills.view", "skills.create",
    "ai.view", "chat.send", "chat.view",
    "admissions", "leaveRequests",
    "aiExamGenerator", "aiTimetable",
    "academics.view", "academics.manage",
    "exams.view", "exams.create", "exams.update", "exams.delete",
    "marks.view", "marks.create", "marks.update", "marks.delete",
    "payroll.view", "payroll.manage",
    "leave.view", "leave.manage",
    "finance.view", "finance.create", "finance.update", "finance.delete",
    "timetable.view", "timetable.create",
    "operations.view", "operations.manage",
    "communication.view", "communication.send", "communication.manage",
    "subscriptions.view", "subscriptions.create", "subscriptions.update",
  ],
  teacher: [
    "students.view",
    "attendance.view", "attendance.create",
    "dashboard.view", "analytics.view",
    "homework.create", "homework.view",
    "assignments.view", "assignments.create", "assignments.grade",
    "quizzes.view", "quizzes.create",
    "lessonPlans.create", "lessonPlans.view",
    "videoLectures.view", "videoLectures.create",
    "bookCenter.view",
    "behavior.view", "behavior.create",
    "skills.view", "skills.create",
    "ai.view", "chat.send", "chat.view",
    "exams.view", "marks.view", "marks.create", "marks.update",
    "timetable.view",
    "communication.send",
  ],
  accountant: [
    "fees.view", "fees.create", "fees.update",
    "billing.view",
    "ledger.view",
    "dashboard.view", "analytics.view",
  ],
  parent: [
    "parents.view", "parents.manage",
  ],
};

export type Role = keyof typeof ROLE_PERMISSIONS;
