import type { CreateStaffDTO, UpdateStaffDTO } from "@/dto";
import type { StaffStatus } from "@/entities/staff.entity";
import type { StaffEntity } from "@/entities/staff.entity";
import type { StaffDocument } from "@/documents/StaffDocument";

export class StaffPersistenceMapper {
  static fromDTO(dto: Partial<CreateStaffDTO>): Partial<StaffEntity> {
    return {
      identity: {
        personnelNo: dto.professional?.personnelNo || "",
        employeeId: dto.professional?.employeeId,
        cnic: dto.personal?.cnic,
      },
      personal: {
        fullName: dto.personal?.fullName || "",
        fatherName: dto.personal?.fatherName,
        dob: dto.personal?.dob,
        gender: dto.personal?.gender,
        bloodGroup: dto.personal?.bloodGroup,
        nationality: dto.personal?.nationality,
        religion: dto.personal?.religion,
        maritalStatus: dto.personal?.maritalStatus,
        photo: dto.personal?.photo,
      },
      contact: dto.contact,
      professional: dto.professional,
      payroll: dto.payroll,
      academic: dto.academic,
      documents: dto.documents,
      emergency: dto.emergency ? {
        name: dto.emergency.name,
        relation: dto.emergency.relation,
        phone: dto.emergency.phone,
        alternatePhone: dto.emergency.alternatePhone,
      } : undefined,
      performance: dto.performance,
      status: 'active' as const,
      campus: dto.professional?.department,
      category: dto.professional?.employmentType,
      metadata: {
        version: dto.metadata?.version || 1,
        source: dto.metadata?.source,
      }
    };
  }

  static toFirestore(entity: Partial<StaffEntity>, userId: string): StaffDocument {
    const doc: StaffDocument = {
      personnelNo: entity.identity?.personnelNo || "",
      employeeId: entity.identity?.employeeId,
      cnic: entity.identity?.cnic,
      fullName: entity.personal?.fullName || "",
      fatherName: entity.personal?.fatherName,
      dob: entity.personal?.dob,
      gender: entity.personal?.gender,
      bloodGroup: entity.personal?.bloodGroup,
      nationality: entity.personal?.nationality,
      religion: entity.personal?.religion,
      maritalStatus: entity.personal?.maritalStatus,
      photo: entity.personal?.photo,
      mobile: entity.contact?.mobile,
      whatsapp: entity.contact?.whatsapp,
      email: entity.contact?.email,
      currentAddress: entity.contact?.currentAddress,
      permanentAddress: entity.contact?.permanentAddress,
      city: entity.contact?.city,
      province: entity.contact?.province,
      country: entity.contact?.country,
      postalCode: entity.contact?.postalCode,
      designation: entity.professional?.designation || "",
      department: entity.professional?.department,
      role: entity.professional?.role,
      employmentType: entity.professional?.employmentType,
      joiningDate: entity.professional?.joiningDate,
      confirmationDate: entity.professional?.confirmationDate,
      experience: entity.professional?.experience,
      qualification: entity.professional?.qualification,
      basicSalary: entity.payroll?.basicSalary,
      allowances: entity.payroll?.allowances,
      deductions: entity.payroll?.deductions,
      grossSalary: entity.payroll?.grossSalary,
      netSalary: entity.payroll?.netSalary,
      bankName: entity.payroll?.bankName,
      accountNumber: entity.payroll?.accountNumber,
      iban: entity.payroll?.iban,
      salaryPaymentMethod: entity.payroll?.salaryPaymentMethod,
      subjects: entity.academic?.subjects,
      classesAssigned: entity.academic?.classesAssigned,
      timetable: entity.academic?.timetable,
      sectionAssignment: entity.academic?.sectionAssignment,
      classTeacher: entity.academic?.classTeacher,
      presentDays: entity.attendance?.presentDays,
      absentDays: entity.attendance?.absentDays,
      lateArrivals: entity.attendance?.lateArrivals,
      leaves: entity.attendance?.leaves,
      attendancePercent: entity.attendance?.attendancePercent,
      casualLeaves: entity.leaves?.casualLeaves,
      medicalLeaves: entity.leaves?.medicalLeaves,
      annualLeaves: entity.leaves?.annualLeaves,
      remainingLeaves: entity.leaves?.remainingLeaves,
      cnicFront: entity.documents?.cnicFront,
      cnicBack: entity.documents?.cnicBack,
      degreeCertificates: entity.documents?.degreeCertificates,
      experienceCertificates: entity.documents?.experienceCertificates,
      appointmentLetter: entity.documents?.appointmentLetter,
      contract: entity.documents?.contract,
      cv: entity.documents?.cv,
      emergencyName: entity.emergency?.name,
      emergencyRelation: entity.emergency?.relation,
      emergencyPhone: entity.emergency?.phone,
      emergencyAlternatePhone: entity.emergency?.alternatePhone,
      score: entity.performance?.score,
      principalRemarks: entity.performance?.principalRemarks,
      warnings: entity.performance?.warnings,
      achievements: entity.performance?.achievements,
      promotions: entity.performance?.promotions,
      trainingHistory: entity.performance?.trainingHistory,
      status: entity.status,
      campus: entity.campus,
      category: entity.category,
      statusHistory: entity.statusHistory,
      tenantId: entity.metadata?.createdBy ? undefined : undefined,
      admissionMethod: undefined,
      metadata: {
        version: entity.metadata?.version || 1,
        source: entity.metadata?.source,
        createdBy: userId,
        updatedBy: userId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }
    };
    return doc;
  }

  static fromFirestore(doc: StaffDocument): StaffEntity {
    const fullName = doc.fullName || "";
    const nameParts = fullName.split(" ");
    const firstName = nameParts[0] || "";
    const lastName = nameParts.slice(1).join(" ") || "";

    return {
      staffId: doc.id || "",
      id: doc.id || "",
      identity: {
        personnelNo: doc.personnelNo || "",
        employeeId: doc.employeeId,
        cnic: doc.cnic,
      },
      personal: {
        fullName: doc.fullName || "",
        fatherName: doc.fatherName,
        dob: doc.dob,
        gender: doc.gender as 'Male' | 'Female' | 'Other' | undefined || 'Male',
        bloodGroup: doc.bloodGroup,
        nationality: doc.nationality,
        religion: doc.religion,
        maritalStatus: doc.maritalStatus as 'Single' | 'Married' | 'Divorced' | 'Widowed' | undefined,
        photo: doc.photo,
      },
      contact: {
        mobile: doc.mobile,
        whatsapp: doc.whatsapp,
        email: doc.email,
        currentAddress: doc.currentAddress,
        permanentAddress: doc.permanentAddress,
        city: doc.city,
        province: doc.province,
        country: doc.country,
        postalCode: doc.postalCode,
      },
      professional: {
        personnelNo: doc.personnelNo || "",
        employeeId: doc.employeeId,
        designation: doc.designation || "",
        department: doc.department,
        role: doc.role,
        employmentType: doc.employmentType,
        joiningDate: doc.joiningDate,
        confirmationDate: doc.confirmationDate,
        experience: doc.experience,
        qualification: doc.qualification,
      },
      payroll: {
        basicSalary: doc.basicSalary,
        allowances: doc.allowances,
        deductions: doc.deductions,
        grossSalary: doc.grossSalary,
        netSalary: doc.netSalary,
        bankName: doc.bankName,
        accountNumber: doc.accountNumber,
        iban: doc.iban,
        salaryPaymentMethod: doc.salaryPaymentMethod,
      },
      academic: {
        subjects: doc.subjects,
        classesAssigned: doc.classesAssigned,
        timetable: doc.timetable,
        sectionAssignment: doc.sectionAssignment,
        classTeacher: doc.classTeacher,
      },
      attendance: {
        presentDays: doc.presentDays,
        absentDays: doc.absentDays,
        lateArrivals: doc.lateArrivals,
        leaves: doc.leaves,
        attendancePercent: doc.attendancePercent,
      },
      leaves: {
        casualLeaves: doc.casualLeaves,
        medicalLeaves: doc.medicalLeaves,
        annualLeaves: doc.annualLeaves,
        remainingLeaves: doc.remainingLeaves,
      },
      documents: {
        cnicFront: doc.cnicFront,
        cnicBack: doc.cnicBack,
        degreeCertificates: doc.degreeCertificates,
        experienceCertificates: doc.experienceCertificates,
        appointmentLetter: doc.appointmentLetter,
        contract: doc.contract,
        cv: doc.cv,
      },
      emergency: {
        name: doc.emergencyName,
        relation: doc.emergencyRelation,
        phone: doc.emergencyPhone,
        alternatePhone: doc.emergencyAlternatePhone,
      },
      performance: {
        score: doc.score,
        principalRemarks: doc.principalRemarks,
        warnings: doc.warnings,
        achievements: doc.achievements,
        promotions: doc.promotions,
        trainingHistory: doc.trainingHistory,
      },
      status: (doc.status as StaffStatus) || 'active',
      campus: doc.campus,
      category: doc.category,
      statusHistory: doc.statusHistory,
      metadata: {
        version: doc.metadata?.version ?? 1,
        source: doc.metadata?.source ?? "web",
        createdBy: doc.metadata?.createdBy,
        updatedBy: doc.metadata?.updatedBy,
        createdAt: doc.metadata?.createdAt,
        updatedAt: doc.metadata?.updatedAt,
      },
      // Legacy compat
      tenantId: doc.tenantId,
      createdBy: doc.metadata?.createdBy,
      updatedBy: doc.metadata?.updatedBy,
      createdAt: doc.metadata?.createdAt,
      updatedAt: doc.metadata?.updatedAt,
      deletedAt: undefined,
    };
  }
}
